linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
    enabled-tags:
      - performance
  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - gomnd
    - golint
    - gofumpt
    - maligned
    - scopelint
    - forbidigo
    - interfacer
  fast: false
