linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - varnamelen
    - nonamedreturns
  fast: false
