run:
  go: '1.19'

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - nonamedreturns
    - testpackage
    - exhaustruct
    - varnamelen
    - forbidigo
    - gofumpt
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - funlen
        - ifshort
        - unparam
        - bodyclose
